name: PR Size Watcher
on: [pull_request]

jobs:
  build:
    name: Check PR size
    runs-on: ubuntu-latest
    steps:
      - uses: ookami-kb/gh-pr-size-watcher@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }} # required
          errorSize: 500 # optional
          errorMessage: ':no_entry: PR has more than **{allowed} additions**. Split it into smaller PRs.'
          warningSize: 333 # optional
          warningMessage: ':warning: PR has more than **{allowed} additions**. Consider splitting it into smaller PRs.'
          excludePaths:  |
            *.md
